name: Robot Framework CI/CD

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: ⬇️ Checkout do Repositório
        uses: actions/checkout@v4

      - name: 🐍 Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: 📦 Instalar Dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: 🌐 Configurar Chrome e Display Virtual (Xvfb)
        run: |
          sudo apt-get update
          sudo apt-get install -y xvfb

      - name: 📁 Criar pastas de resultados
        run: |
          mkdir -p allure-results
          mkdir -p logs

      - name: 🤖 Executar Testes em Paralelo (Pabot)
        continue-on-error: true
        run: |
          xvfb-run --auto-servernum --server-args="-screen 0 1920x1080x24" \
          pabot --processes 4 -d ./logs --listener allure_robotframework:$PWD/allure-results --variable BROWSER:headlesschrome test/features/
      - name: 📥 Baixar Histórico do Allure (Trend)
        uses: actions/checkout@v4
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: 📊 Gerar Allure Report
        uses: simple-elf/allure-report-action@master
        if: always()
        id: allure-report
        with:
          allure_results: allure-results
          gh_pages: gh-pages
          allure_report: allure-report
          allure_history: allure-history
          keep_histories: 20

      - name: 🚀 Publicar no GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-history